name: Laravel CI/CD

on:
  push:
    branches:
      - live  # Change this to your project's main branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Latest Changes
        run: git pull origin live
        
      # - name: Run Tests
      #   run: vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Production
        run: |
            # Set up the SSH key for authentication
            echo "GITHUB_REPOSITORY_value_echo: $SSH_PRIVATE_KEY"
            # echo $SSH_PRIVATE_KEY
            # echo "$SSH_PRIVATE_KEY" > deploy_key
            # chmod 600 deploy_key
            # ssh -i deploy_key donatepu@141.95.99.203 'cd /home/donatepu/public_html && git pull origin live'
            # echo "Deployment to production completed successfully"
            # Save your private key to a file (e.g., id_rsa)
            # Start the SSH agent
            eval "$(ssh-agent -s)"

            # Save your private key to a file (e.g., id_rsa)
            echo "$SSH_PRIVATE_KEY" > id_rsa

            # Set appropriate file permissions
            chmod 600 id_rsa

            # Add the key to the SSH agent
            ssh-add id_rsa

            # Use the key for SSH operations
            # ssh donatepu@141.95.99.203 'cd /home/donatepu/public_html && git pull origin live'
            ssh donatepu@141.95.99.203






    # deploy:
    #   runs-on: ubuntu-latest
    #   needs: build
    #   steps:
    #     - name: Deploy to Production
    #       run: |
    #         # Set up the SSH key for authentication
    #         echo "$SSH_PRIVATE_KEY" > deploy_key
    #         chmod 600 deploy_key
    #         ssh -i deploy_key donatepu@141.95.99.203 'cd /home/donatepu/public_html && git pull origin live'
    #         echo "Deployment to production completed successfully"
    #       env:
    #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

