name: Laravel CI/CD

on:
  push:
    branches:
      - live  # Change this to your project's main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
         submodules: 'recursive'
         runs-on: ubuntu-latest

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Change this to the PHP version your project requires

      - name: Install Composer Dependencies
        run: composer install

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Database Migrations and Seed
        run: php artisan migrate --seed

      - name: Run Tests
        run: vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Production
        run: |
          # Add your deployment script or commands here
          # For example, deploying to a web server using SSH or other methods
