name: Laravel CI/CD

on:
  push:
    branches:
      - live  # Change this to your project's main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use Node.js 16

      - name: Checkout code
        uses: actions/checkout@v2



  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Production
        run: |
          # Add your deployment script or commands here
