name: Laravel CI/CD

on:
  push:
    branches:
      - live  # Change this to your project's main branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Latest Changes
        run: git pull origin live
        
      # - name: Run Tests
      #   run: vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Production
        run: |
          # Add your deployment script or commands here
          git pull origin live
          
          echo "Deployment to production completed successfully"


